import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { FcGoogle } from "react-icons/fc";
import { FaApple } from "react-icons/fa";
import { signIn, useSession } from 'next-auth/react';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
const {data: session} = useSession();
const handleLogin = async (provider) => {
  try {
    await signIn(provider, { callbackUrl: `${window.location.origin}/dashboard` });
  } catch (err) {
    console.log(err);
  }
  };

  return (
    <>
      <Head>
        <title>Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row">
        <div className="col1">
          <div className="heading">Board.</div>
        </div>
        <div className="col2">
          <div className="form-div">
            <div>
              <div className="head1">Sign In</div>
              <div className="head2">Sign in to your account</div>
            </div>

            <div className="btn">
              <button onClick={()=> handleLogin('google')}>
                <FcGoogle />
                Sign in with Google
              </button>
              <button>
                <FaApple />
                Sign in with Apple
              </button>
            </div>

            <form className="form">
              <label htmlFor="email">Email address</label>
              <input type="email" name="email" id="email" />
              <label htmlFor="password">Password</label>

              <input type="password" name="password" id="password" />
              <p className="text1">Forgot Password?</p>
              <button type="submit" className="sign-in">Sign In</button>
            </form>
            <p className="text2">Don't have an account?<a href=""> Register Here</a></p>

          </div>
        </div>
      </div>
    </>
  );
}
